### ISSUE TITLE
Design and Implement Prototypes

### ISSUE THREAD

**Issue by Ziyad-Zanbagi** [RestarauntView-CPIT405-Project/RestView#2]
After the sketches, we will implement the prototypes:
- [x] Implement in HTML
   - [x] Home Page 
   - [x] Sign in/Sign up
   - [x] Review Page

Then:

- [x] Implement in CSS

**Comment by KhalidAlghamdi12** [comment]
https://github.com/RestarauntView-CPIT405-Project/RestView/commit/b9ceb9ed7381f4af8cc515645b1238ffe9b9ad3b

I implemented the sketches in HTML - CSS 
for the index page : 
CSS - HTML in the same file 

Fore other pages : there is they are separate
